function skillsMember() {
  var member = new Member();
  member.skills = [
    new Skill('JavaScript', 10),
    new Skill('HTML', 10),
    new Skill('CSS', 10),
    new Skill('Node.js', 9),
    new Skill('React', 9),
    new Skill('Angular', 8),
    new Skill('Vue.js', 8),
    new Skill('TypeScript', 8),
    new Skill('Sass', 8),
    new Skill('Webpack', 8),
    new Skill('Gulp', 8),
    new Skill('Grunt', 8),
    new Skill('Express', 8),
    new Skill('MongoDB', 8),
    new Skill('MySQL', 8),
    new Skill('PostgreSQL', 8),
    new Skill('SQLite', 8),
    new Skill('Redis', 8),
    new Skill('GraphQL', 8),
    new Skill('RESTful API', 8),
    new Skill('JSON', 8),
    new Skill('XML', 8),
    new Skill('OAuth', 8),
    new Skill('JWT', 8),
    new Skill('WebSocket', 8),
    new Skill('WebRTC', 8),
    new Skill('Progressive Web Apps', 8),
    new Skill('Service Workers', 8),
    new Skill('Push Notifications', 8),
    new Skill('Web Sockets', 8),
    new Skill('WebRTC', 8),
    new Skill('Web Workers', 8),
    new Skill('IndexedDB', 8),
    new Skill('File API', 8),
    new Skill('History API', 8),
    new Skill('WebRTC', 8),
    new Skill('WebGL', 8),
    new Skill('WebVR', 8),
    new Skill('Web Audio API', 8),
    new Skill('Web Speech API', 8),
    new Skill('WebMIDI', 8),
    new Skill('WebRTC', 8),
    new Skill('WebVR', 8),
    new Skill('WebXR', 8),
    new Skill('WebGL', 8),
    new Skill('WebGPU', 8),
    new Skill('WebCL', 8),
    new Skill('WebAssembly', 8),
    new Skill('Web Workers', 8),
    new Skill('Service Workers